name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies (mobile)
        working-directory: ./mobile
        run: npm install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android APK
        working-directory: ./mobile
        run: |
          npx expo export:embed --platform android --dev false
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/android/app/build/outputs/apk/release/*.apk